spring:
  application:
    name: SERVICE-REGISTRY

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  username: ${EUREKA_USERNAME:admin}
  password: ${EUREKA_PASSWORD:admin}