spring:
  application:
    name: API-GATEWAY
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/travel-booking
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: TOUR-SERVICE
          uri: lb://TOUR-SERVICE
          predicates:
            - Path=/api/v1/tours/**, /tour-service/v3/api-docs
        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/bookings/**, /booking-service/v3/api-docs
        - id: INVENTORY-SERVICE
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**, /inventory-service/v3/api-docs
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**, /payment-service/v3/api-docs
        - id: REVIEW-SERVICE
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/v1/reviews/**, /review-service/v3/api-docs
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**, /account-service/v3/api-docs
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**, /notification-service/v3/api-docs
          # discovery server route
        - id: DISCOVERY-SERVER
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/dashboard
          filters:
            - SetPath=/
        - id: DISCOVERY-SERVER-STATIC
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

server:
  port: 9191

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      springframework:
        web: DEBUG

jwt:
  auth:
    converter:
      resource-id: travel-booking-client
      principle-attribute: preferred_username

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Tour Service
        url: /tour-service/v3/api-docs
      - name: Review Service
        url: /review-service/v3/api-docs
      - name: Payment Service
        url: /payment-service/v3/api-docs
      - name: Notification Service
        url: /notification-service/v3/api-docs
      - name: Inventory Service
        url: /inventory-service/v3/api-docs
      - name: Booking Service
        url: /booking-service/v3/api-docs
      - name: Account Service
        url: /account-service/v3/api-docs