spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: STORAGE-SERVICE

server:
  port: 9002

minio:
  url: http://localhost:9000
  username: ${MINIO_USERNAME}
  password: ${MINIO_PASSWORD}
  bucket:
    name: travel-booking-storage
  part:
    size: -1