#spring:
#  datasource:
#    url: ${DB_URL}/travel-tour-service
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        search:
#          schema_management:
#            strategy:
#          backend:
#            type: elasticsearch
#            uris: http://localhost:9200
#    hibernate:
#      ddl-auto: update
#      show-sql: always
#  application:
#    name: TOUR-SERVICE
#  jackson:
#    time-zone: Asia/Ho_Chi_Minh
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 100MB
#      max-request-size: 100MB
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://admin:admin@localhost:8761/eureka/
#
#management:
#  tracing:
#    sampling:
#      probability: 1.0
#
#logging:
#  pattern:
#    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
#  level:
#    org:
#      springframework:
#        web: DEBUG
#
#minio:
#  bucket:
#    name: travel-booking-storage
#
#server:
#  tomcat:
#    relaxed-query-chars: '|,{,},[,]'

spring:
  application:
    name: TOUR-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/travel-booking
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: travel-booking-client
      principle-attribute: preferred_username