spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_REPO_URI}
          clone-on-start: true
          default-label: ${GIT_BRANCH}

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

